# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Thoughts on Social Software Entrepreneurialism
logo:               # Logo image URL
email:              alb@andrewlb.com
description:        Writings by Andrew Lovett-Barron
baseurl:            '' # The subpath of your site, e.g. /blog
url:                'http://log.andrewlb.com' # The base hostname & protocol for your site
github_username:    readywater
twitter_username:   readywater
instagram_username: readywater

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Andrew:
    name:             Andrew Lovett-Barron
    bio:              Product Designer. New America Fellow; previously USDS and IDEO
    gravatar:         
    email:            alb@andrewlb.com
    website:          http://andrewlb.com
    github_username:  readywater
    twitter_username: readywater
